/// Flutter icons Elusive
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Elusive
///      fonts:
///       - asset: fonts/Elusive.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class Elusive {
  Elusive._();

  static const _kFontFam = 'Elusive';

  static const IconData glass = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData music = const IconData(0xe802, fontFamily: _kFontFam);
}
